In [3]:
import numpy as np

In [10]:
np.array([1, 2, 3])

array([1, 2, 3])

In [9]:
np.array([[1], [2], [3]])

array([[1],
       [2],
       [3]])

In [8]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
list1 = np.arange(start=1, stop=13, step=1)
list1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
arr = np.array(list1.reshape(3,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
ls1 = [1,2,3]
ls2 = [4,5,6]
arr1 = np.array(ls1)
arr2 = np.array(ls2)
arr1+arr2

array([5, 7, 9])

In [17]:
arr2-arr1

array([3, 3, 3])

In [18]:
arr1 ^ arr2

array([5, 7, 5])

In [19]:
arr1 * arr2

array([ 4, 10, 18])

In [20]:
arr1%arr2

array([1, 2, 3])

In [22]:
arr = np.array([1,2,3,4,5])

In [29]:
norm_l1 = np.linalg.norm(arr, 1)
norm_l1

np.float64(15.0)

In [26]:
arr = np.array([1,2,-3,4,5])

In [30]:
norm_l1 = np.linalg.norm(arr, 1)
norm_l1

np.float64(15.0)

In [31]:
norm_l2 = np.linalg.norm(arr)
norm_l2

np.float64(7.416198487095663)

In [32]:
matrix = np.array([[1,2], [3,4]])

In [34]:
np.linalg.det(matrix)

np.float64(-2.0000000000000004)

In [35]:
mat = np.array([[1,2,1],[3,4,7],[3,6,3]])
mat

array([[1, 2, 1],
       [3, 4, 7],
       [3, 6, 3]])

In [36]:
rank = np.linalg.matrix_rank(mat)
rank

np.int64(2)

In [37]:
A = np.array([[3,7], [2,5]])
A

array([[3, 7],
       [2, 5]])

In [39]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 5., -7.],
       [-2.,  3.]])